name: frontend storybook deploy Workflow
on:
  pull_request:
    branches:
      - '**'
    paths: ['frontend/**/*.stories.ts', 'frontend/**/*.stories.tsx']

defaults:
  run:
    working-directory: frontend

jobs:
  timeout-minutes: 10
  runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [20.x]

  steps:
    # 해당 저장소의 코드를 가져온다
    - name: Checkout
      uses: actions/checkout@v4

    # 스토리북 배포
    - name: Install dependencies
      run: npx chromatic --project-token=chpt_8356e0761461580
